# Generated by Django 5.1.1 on 2024-09-22 09:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesAndReviews', '0002_alter_author_pseudonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
