# Generated by Django 5.1.1 on 2024-09-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesAndReviews', '0006_alter_author_favorite_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorite_games',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_by', to='gamesAndReviews.game'),
        ),
    ]
